# Site settings
title: Stavros Kounis âŽ
fullname: Stavros Kounis
slogan_short: Software developer and JavaScript enthusiast.
slogan: Software developer and JavaScript enthusiast, passioned with web and mobile technologies.
email: skounis [at] gmail [dot] com
age: 40
address: E. Venizelou 70, 67100, Xanthi, GR
skype: skounis
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
latitude: 41.1410369
longitude: 24.8862945
twitter_username: jekyllrb
github_username:  jekyll
social_twitter: https://twitter.com/skounis
social_linkedin:  https://gr.linkedin.com/in/stavroskounis
social_gplus: https://plus.google.com/u/0/+StavrosKounis
social_instagram: https://www.instagram.com/skounis/
social_medium: https://medium.com/@skounis
calendly: https://calendly.com/skounis/
# Build settings
markdown: kramdown
